
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ve.edu.unet;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 27;
  public static final int MOD = 29;
  public static final int READ = 11;
  public static final int AND = 13;
  public static final int OVER = 28;
  public static final int LT = 20;
  public static final int ELSE = 7;
  public static final int PLUS = 25;
  public static final int RPAREN = 31;
  public static final int OR = 15;
  public static final int LTE = 22;
  public static final int THEN = 6;
  public static final int SEMI = 32;
  public static final int NOT = 14;
  public static final int END = 8;
  public static final int IF = 5;
  public static final int LPAREN = 30;
  public static final int GT = 21;
  public static final int GTE = 23;
  public static final int WRITE = 12;
  public static final int ID = 16;
  public static final int NUM = 17;
  public static final int DO = 4;
  public static final int EOF = 0;
  public static final int MINUS = 26;
  public static final int error = 1;
  public static final int EQ = 19;
  public static final int ASSIGN = 18;
  public static final int UNTIL = 10;
  public static final int BOOL = 33;
  public static final int FOR = 2;
  public static final int NEQ = 24;
  public static final int TO = 3;
  public static final int REPEAT = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FOR",
  "TO",
  "DO",
  "IF",
  "THEN",
  "ELSE",
  "END",
  "REPEAT",
  "UNTIL",
  "READ",
  "WRITE",
  "AND",
  "NOT",
  "OR",
  "ID",
  "NUM",
  "ASSIGN",
  "EQ",
  "LT",
  "GT",
  "LTE",
  "GTE",
  "NEQ",
  "PLUS",
  "MINUS",
  "TIMES",
  "OVER",
  "MOD",
  "LPAREN",
  "RPAREN",
  "SEMI",
  "BOOL"
  };
}

